import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'ar' | 'en' | 'fr';
type Direction = 'rtl' | 'ltr';

interface LanguageContextType {
    language: Language;
    direction: Direction;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    ar: {
        settings_title: "الإعدادات",
        settings_desc: "تخصيص النظام وإعدادات الحساب",
        general: "عام",
        profile: "الملف الشخصي",
        security: "الأمان",
        notifications_title: "الإشعارات",
        notifications_desc: "التحكم في استقبال الإشعارات والتنبيهات",
        notifications_enable: "تفعيل الإشعارات",
        notifications_subtext: "استقبل تنبيهات حول الرصيد، الشكاوى، والعمليات",
        theme_title: "المظهر",
        theme_desc: "اختر مظهر التطبيق المفضل لديك",
        theme_light: "وضع نهاري",
        theme_dark: "وضع ليلي",
        theme_system: "النظام",
        language_title: "اللغة",
        language_desc: "تغيير لغة واجهة المستخدم",
        language_select: "اختر اللغة",
        profile_title: "المعلومات الشخصية",
        profile_desc: "بيانات حسابك الحالية",
        full_name: "الاسم الكامل",
        email: "البريد الإلكتروني",
        role: "الدور الصلاحي",
        security_title: "كلمة المرور والأمان",
        security_desc: "تغيير كلمة المرور الخاصة بك",
        current_password: "كلمة المرور الحالية",
        new_password: "كلمة المرور الجديدة",
        update_password: "تحديث كلمة المرور",
        referral_code_title: "رمز دعوة تجار التجزئة",
        referral_code_desc: "هذا الرمز صالح لمدة 10 دقائق فقط. شاركه مع تجار التجزئة لربطهم بحسابك تلقائيًا",
        generate_code: "إنشاء رمز جديد",
        generating_code: "جاري إنشاء الرمز...",
        copy_code: "نسخ الرمز",
        update_code: "تحديث الرمز",
        code_copied: "تم نسخ الرمز",
        code_generated: "تم إنشاء رمز الدعوة بنجاح",
        code_error: "حدث خطأ أثناء إنشاء الرمز",
        role_super_admin: "المدير العام",
        role_wholesaler: "تاجر جملة",
        role_retailer: "تاجر تجزئة",
        role_super_wholesaler: "تاجر جملة ممتاز",
        role_user: "مستخدم",
        search_placeholder: "بحث في المعاملات، المستخدمين...",
        notifications_new: "جديد",
        notifications_empty: "لا توجد تنبيهات جديدة",
        clear_all: "مسح الكل",
        // Sidebar
        nav_dashboard: "الرئيسية",
        nav_financials: "المالية",
        nav_users: "إدارة المستخدمين",
        nav_sims: "إدارة الشرائح",
        nav_offers: "عروض المتعاملين",
        nav_games: "شحن الألعاب",
        nav_delivery: "تطبيقات التوصيل",
        nav_notifications: "الإشعارات",
        nav_complaints: "الشكاوي",
        nav_transactions: "سجل العمليات",
        nav_recharge: "شحن رصيد",
        nav_balance: "رصيدي",
        nav_logout: "تسجيل الخروج",
        nav_settings: "الإعدادات",
        // Financials
        fin_title: "المالية",
        fin_header_desc: "لوحة القيادة المالية والتحليلات",
        fin_period_placeholder: "اختر المدة",
        fin_period_7: "آخر 7 أيام",
        fin_period_30: "آخر 30 يوم",
        fin_period_90: "آخر 90 يوم",
        fin_current_balance: "رصيدك الحالي",
        fin_available_balance: "الرصيد المتوفر في محفظتك",
        fin_debt: "الديون التي عليك",
        fin_retailers_balance: "أرصدة تجار التجزئة",
        fin_retailers_balance_desc: "إجمالي الأرصدة المتوفرة لديهم",
        fin_volume: "حجم تداولات الفترة",
        fin_low_balance: "أرصدة منخفضة",
        fin_low_balance_desc: "تجار بحاجة لإعادة شحن (أقل من 5000 د.ج)",
        fin_active_retailers: "الأكثر نشاطاً",
        fin_active_retailers_desc: "أفضل تجار التجزئة من حيث حجم التعاملات",
        fin_chart_title: "النشاط المالي",
        fin_chart_desc: "حجم التعاملات اليومية خلال الفترة المحددة",
        fin_no_data: "لا توجد بيانات كافية",
        // Recharge
        recharge_title: "بيع رصيد",
        recharge_header_desc: "شحن فليكسي أو تفعيل عروض",
        recharge_data_title: "بيانات العملية",
        recharge_phone_label: "رقم الهاتف",
        recharge_flexy: "فليكسي (مبلغ حر)",
        recharge_offers: "عروض (Internet/Calls)",
        recharge_amount_label: "المبلغ (د.ج)",
        recharge_choose_offer: "اختر العرض",
        recharge_no_operator: "يرجى اختيار المتعامل أولاً",
        recharge_submit_flexy: "تأكيد العملية",
        recharge_submit_offer: "تفعيل العرض",
        recharge_internet_title: "شحن الإنترنت",
        recharge_games_title: "شحن الألعاب",
        recharge_soon: "قريباً",
        recharge_buy_card: "شراء البطاقة",
        // Dashboard
        dash_total_transactions: "إجمالي العمليات اليوم",
        dash_total_revenue: "إجمالي الإيرادات",
        dash_active_dealers: "المكاتب النشطة",
        dash_current_balance: "الرصيد الحالي",
        dash_geo_title: "أكثر البلديات نشاطاً",
        dash_geo_revenue: "الإيرادات",
        dash_offers_title: "العروض الأكثر طلباً",
        dash_time_title: "تحليل النشاط الزمني (أوقات الذروة)",
        dash_time_tooltip: "الساعة",
        dash_dealers_title: "أفضل المتعاملين أداءً",
        dash_system_health: "حالة النظام المالية",
        dash_system_balance: "إجمالي الأرصدة في النظام",
        dash_safe_stable: "آمن ومستقر",
        dash_low_balance_alert: "تنبيهات الأرصدة المنخفضة ستظهر هنا",
        dash_loading: "جاري تحميل البيانات...",
        dash_error: "فشل تحميل البيانات",
        dash_vs_yesterday: "مقارنة بالأمس",
        dashboard_title: "لوحة التحكم",
        dashboard_welcome: "مرحباً بك،",
        sims_wholesaler_balance: "إجمالي أرصدة تجار الجملة",
        sims_retailer_balance: "إجمالي أرصدة تجار التجزئة",
        sims_system_deficit: "عجز في النظام!",
        sims_deficit_alert: "مجموع أرصدة الجملة والتجزئة يفوق الرصيد الفعلي للشرائح!",
        sims_operator_balances: "أرصدة المتعاملين",
        sims_total_sims: "إجمالي رصيد الشرائح",
    },
    en: {
        settings_title: "Settings",
        settings_desc: "Customize system and account settings",
        general: "General",
        profile: "Profile",
        security: "Security",
        notifications_title: "Notifications",
        notifications_desc: "Manage notifications and alerts",
        notifications_enable: "Enable Notifications",
        notifications_subtext: "Receive alerts about balance, complaints, and transactions",
        theme_title: "Theme",
        theme_desc: "Choose your preferred app theme",
        theme_light: "Light Mode",
        theme_dark: "Dark Mode",
        theme_system: "System",
        language_title: "Language",
        language_desc: "Change user interface language",
        language_select: "Select Language",
        profile_title: "Personal Information",
        profile_desc: "Your current account details",
        full_name: "Full Name",
        email: "Email Address",
        role: "User Role",
        security_title: "Password & Security",
        security_desc: "Change your password",
        current_password: "Current Password",
        new_password: "New Password",
        update_password: "Update Password",
        referral_code_title: "Retailer Invitation Code",
        referral_code_desc: "This code is valid for 10 minutes only. Share it with retailers to link them automatically.",
        generate_code: "Generate New Code",
        generating_code: "Generating...",
        copy_code: "Copy Code",
        update_code: "Refresh Code",
        code_copied: "Code copied",
        code_generated: "Invitation code generated successfully",
        code_error: "Error generating code",
        role_super_admin: "Super Admin",
        role_wholesaler: "Wholesaler",
        role_retailer: "Retailer",
        role_super_wholesaler: "Super Wholesaler",
        role_user: "User",
        search_placeholder: "Search transactions, users...",
        notifications_new: "New",
        notifications_empty: "No new notifications",
        clear_all: "Clear All",
        // Sidebar
        nav_dashboard: "Dashboard",
        nav_financials: "Financials",
        nav_users: "Users Management",
        nav_sims: "SIM Management",
        nav_offers: "Offers",
        nav_games: "Games Recharge",
        nav_delivery: "Delivery Apps",
        nav_notifications: "Notifications",
        nav_complaints: "Complaints",
        nav_transactions: "Transactions",
        nav_recharge: "Recharge Balance",
        nav_balance: "My Balance",
        nav_logout: "Logout",
        nav_settings: "Settings",
        // Financials
        fin_title: "Financials",
        fin_header_desc: "Financial dashboard and analytics",
        fin_period_placeholder: "Select Period",
        fin_period_7: "Last 7 days",
        fin_period_30: "Last 30 days",
        fin_period_90: "Last 90 days",
        fin_current_balance: "Current Balance",
        fin_available_balance: "Available balance",
        fin_debt: "Your Debt",
        fin_retailers_balance: "Retailers Balance",
        fin_retailers_balance_desc: "Total available balance",
        fin_volume: "Period Volume",
        fin_low_balance: "Low Balance",
        fin_low_balance_desc: "Retailers needing recharge (< 5000 DZD)",
        fin_active_retailers: "Most Active",
        fin_active_retailers_desc: "Top retailers by volume",
        fin_chart_title: "Financial Activity",
        fin_chart_desc: "Daily transaction volume",
        fin_no_data: "No sufficient data",
        // Recharge
        recharge_title: "Sell Balance",
        recharge_header_desc: "Flexy recharge or offers",
        recharge_data_title: "Transaction Details",
        recharge_phone_label: "Phone Number",
        recharge_flexy: "Flexy (Custom Amount)",
        recharge_offers: "Offers (Internet/Calls)",
        recharge_amount_label: "Amount (DZD)",
        recharge_choose_offer: "Select Offer",
        recharge_no_operator: "Please select operator first",
        recharge_submit_flexy: "Confirm Transaction",
        recharge_submit_offer: "Activate Offer",
        recharge_internet_title: "Internet Recharge",
        recharge_games_title: "Games Recharge",
        recharge_soon: "Coming Soon",
        recharge_buy_card: "Buy Card",
        // Dashboard
        dash_total_transactions: "Total Transactions Today",
        dash_total_revenue: "Total Revenue",
        dash_active_dealers: "Active Dealers",
        dash_current_balance: "Current Balance",
        dash_geo_title: "Most Active Regions",
        dash_geo_revenue: "Revenue",
        dash_offers_title: "Top Offers",
        dash_time_title: "Activity Analysis (Peak Times)",
        dash_time_tooltip: "Hour",
        dash_dealers_title: "Top Performing Dealers",
        dash_system_health: "Financial System Health",
        dash_system_balance: "Total System Balance",
        dash_safe_stable: "Safe & Stable",
        dash_low_balance_alert: "Low balance alerts will appear here",
        dash_loading: "Loading data...",
        dash_error: "Failed to load data",
        dash_vs_yesterday: "vs Yesterday",
        dashboard_title: "Dashboard",
        dashboard_welcome: "Welcome,",
        sims_wholesaler_balance: "Total Wholesaler Balance",
        sims_retailer_balance: "Total Retailer Balance",
        sims_system_deficit: "System Deficit!",
        sims_deficit_alert: "Sum of Wholesaler & Retailer balances exceeds Total SIMs Balance!",
        sims_operator_balances: "Operator Balances",
        sims_total_sims: "Total SIMs Balance",
    },
    fr: {
        settings_title: "Paramètres",
        settings_desc: "Personnaliser le système et le compte",
        general: "Général",
        profile: "Profil",
        security: "Sécurité",
        notifications_title: "Notifications",
        notifications_desc: "Gérer les notifications et alertes",
        notifications_enable: "Activer les notifications",
        notifications_subtext: "Recevoir des alertes sur le solde, les plaintes et les transactions",
        theme_title: "Thème",
        theme_desc: "Choisissez votre thème préféré",
        theme_light: "Mode Clair",
        theme_dark: "Mode Sombre",
        theme_system: "Système",
        language_title: "Langue",
        language_desc: "Changer la langue de l'interface",
        language_select: "Choisir la langue",
        profile_title: "Informations Personnelles",
        profile_desc: "Détails de votre compte actuel",
        full_name: "Nom Complet",
        email: "Adresse Email",
        role: "Rôle Utilisateur",
        security_title: "Mot de passe et Sécurité",
        security_desc: "Changer votre mot de passe",
        current_password: "Mot de passe actuel",
        new_password: "Nouveau mot de passe",
        update_password: "Mettre à jour le mot de passe",
        referral_code_title: "Code d'invitation Détaillant",
        referral_code_desc: "Ce code est valide pendant 10 minutes seulement. Partagez-le avec les détaillants pour les lier automatiquement.",
        generate_code: "Générer un nouveau code",
        generating_code: "Génération...",
        copy_code: "Copier le code",
        update_code: "Actualiser le code",
        code_copied: "Code copié",
        code_generated: "Code d'invitation généré avec succès",
        code_error: "Erreur lors de la génération du code",
        role_super_admin: "Super Admin",
        role_wholesaler: "Grossiste",
        role_retailer: "Détaillant",
        role_super_wholesaler: "Super Grossiste",
        role_user: "Utilisateur",
        search_placeholder: "Rechercher transactions, utilisateurs...",
        notifications_new: "Nouveau",
        notifications_empty: "Pas de nouvelles notifications",
        clear_all: "Tout effacer",
        // Sidebar
        nav_dashboard: "Tableau de bord",
        nav_financials: "Finance",
        nav_users: "Gestion utilisateurs",
        nav_sims: "Gestion SIMs",
        nav_offers: "Offres",
        nav_games: "Recharge Jeux",
        nav_delivery: "Livraison",
        nav_notifications: "Notifications",
        nav_complaints: "Réclamations",
        nav_transactions: "Transactions",
        nav_recharge: "Recharger Solde",
        nav_balance: "Mon Solde",
        nav_logout: "Déconnexion",
        nav_settings: "Paramètres",
        // Financials
        fin_title: "Finance",
        fin_header_desc: "Tableau de bord financier et analytique",
        fin_period_placeholder: "Période",
        fin_period_7: "7 derniers jours",
        fin_period_30: "30 derniers jours",
        fin_period_90: "90 derniers jours",
        fin_current_balance: "Solde Actuel",
        fin_available_balance: "Solde disponible",
        fin_debt: "Votre dette",
        fin_retailers_balance: "Solde Détaillants",
        fin_retailers_balance_desc: "Solde total disponible",
        fin_volume: "Volume Période",
        fin_low_balance: "Solde Bas",
        fin_low_balance_desc: "Nécessite recharge (< 5000 DZD)",
        fin_active_retailers: "Plus Actifs",
        fin_active_retailers_desc: "Meilleurs détaillants par volume",
        fin_chart_title: "Activité Financière",
        fin_chart_desc: "Volume quotidien des transactions",
        fin_no_data: "Pas assez de données",
        // Recharge
        recharge_title: "Vendre Solde",
        recharge_header_desc: "Recharge Flexy ou offres",
        recharge_data_title: "Détails Transaction",
        recharge_phone_label: "Numéro de téléphone",
        recharge_flexy: "Flexy (Montant libre)",
        recharge_offers: "Offres (Internet/Appels)",
        recharge_amount_label: "Montant (DZD)",
        recharge_choose_offer: "Choisir Offre",
        recharge_no_operator: "Choisir l'opérateur d'abord",
        recharge_submit_flexy: "Confirmer Transaction",
        recharge_submit_offer: "Activer Offre",
        recharge_internet_title: "Recharge Internet",
        recharge_games_title: "Recharge Jeux",
        recharge_soon: "Bientôt",
        recharge_buy_card: "Acheter Carte",
        // Dashboard
        dash_total_transactions: "Total Transactions Aujourd'hui",
        dash_total_revenue: "Revenu Total",
        dash_active_dealers: "Détaillants Actifs",
        dash_current_balance: "Solde Actuel",
        dash_geo_title: "Régions les plus actives",
        dash_geo_revenue: "Revenu",
        dash_offers_title: "Meilleures Offres",
        dash_time_title: "Analyse d'Activité (Heures de pointe)",
        dash_time_tooltip: "Heure",
        dash_dealers_title: "Meilleurs Détaillants",
        dash_system_health: "Santé Financière du Système",
        dash_system_balance: "Solde Total du Système",
        dash_safe_stable: "Sûr et Stable",
        dash_low_balance_alert: "Alertes de solde bas apparaîtront ici",
        dash_loading: "Chargement des données...",
        dash_error: "Échec du chargement des données",
        dash_vs_yesterday: "vs Hier",
        dashboard_title: "Tableau de Bord",
        dashboard_welcome: "Bienvenue,",
        sims_wholesaler_balance: "Solde Total Grossistes",
        sims_retailer_balance: "Solde Total Détaillants",
        sims_system_deficit: "Déficit Système!",
        sims_deficit_alert: "Le total des soldes dépasse le solde réel des SIMs!",
        sims_operator_balances: "Soldes Opérateurs",
        sims_total_sims: "Solde Total SIMs",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        return (localStorage.getItem('language') as Language) || 'ar';
    });

    const [direction, setDirection] = useState<Direction>('rtl');

    useEffect(() => {
        const dir = language === 'ar' ? 'rtl' : 'ltr';
        setDirection(dir);
        document.documentElement.dir = dir;
        document.documentElement.lang = language;
        localStorage.setItem('language', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
